secret_key = "hejmeddigjeghedderkaj"

[server]
listen_on = "0.0.0.0:9797"
files = [
    { src = "test/server/etc/infod_passwd", dest = "test/client/var/spool/infod/passwd", mode = 0o444 },
    { src = "test/server/etc/infod_group", dest = "test/client/var/spool/infod/group", mode = 0o444 },
    { src = "test/server/etc/infod_shadow", dest = "test/client/var/spool/infod/shadow", mode = 0o000 },
    { src = "test/server/etc/infod_mount", dest = "test/client/var/spool/infod/auto.home", mode = 0o400 },

]

[client]
server = "localhost:9797"
# Default: 1 (seconds)
update_interval = 3.0
