secret_key = "hejmeddigjeghedderkaj"

[server]
listen_on = "0.0.0.0:9797"
files = [
    { src = "/var/spool/infod/passwd", dest = "/var/spool/infod/passwd", mode = 0o644 },
    { src = "/var/spool/infod/group", dest = "/var/spool/infod/group", mode = 0o644 },
    { src = "/var/spool/infod/shadow", dest = "/var/spool/infod/shadow", mode = 0o000 },
    { src = "/var/spool/infod/auto.home", dest = "/var/spool/infod/auto.home", mode = 0o600 },

]

[client]
server = "localhost:9797"
# Default: 1 (seconds)
update_interval = 3.0
